### ISSUE TITLE
Panic on incorrect input in gtpv2 message.Parse

### ISSUE THREAD

**Issue by mogaika** [wmnsk/go-gtp#206]
It is possible to panic on this line:
https://github.com/wmnsk/go-gtp/blob/c6c616cb34d52a5c735f2b2f193c8dcc0deda3f6/gtpv2/message/message.go#L311

Been able to find this with fuzz tests:
https://github.com/mogaika/go-gtp/commit/7fd9e9f776233073c44bfd4ed65d590b1a57ba7c

```
$ go test -fuzz FuzzParse -fuzztime 1m github.com/wmnsk/go-gtp/gtpv2/message
fuzz: elapsed: 0s, gathering baseline coverage: 0/1512 completed
failure while testing seed corpus entry: FuzzParse/582528ddfad69eb57775199a43e0f9fd5c94bba343ce7bb6724d4ebafe311ed4
fuzz: elapsed: 0s, gathering baseline coverage: 2/1512 completed
--- FAIL: FuzzParse (0.06s)
    --- FAIL: FuzzParse (0.00s)
        testing.go:1349: panic: runtime error: index out of range [1] with length 1
            goroutine 16 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x90
            testing.tRunner.func1()
            	/usr/local/go/src/testing/testing.go:1349 +0x1f2
            panic({0x65d520, 0xc00001a270})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/wmnsk/go-gtp/gtpv2/message.Parse({0xc0000167b8?, 0x4c749e?, 0x2?})
            	/home/mogaika/work/github/wmnsk/go-gtp/gtpv2/message/message.go:311 +0xcd3
            github.com/wmnsk/go-gtp/gtpv2/message_test.FuzzParse.func1(0xc000113860, {0xc0000167b8?, 0x0?, 0x4647d9?})
            	/home/mogaika/work/github/wmnsk/go-gtp/gtpv2/message/message_test.go:25 +0x2c
            reflect.Value.call({0x63b1a0?, 0x68b0d0?, 0x13?}, {0x67a5ed, 0x4}, {0xc00007cea0, 0x2, 0x2?})
            	/usr/local/go/src/reflect/value.go:556 +0x845
            reflect.Value.Call({0x63b1a0?, 0x68b0d0?, 0x514?}, {0xc00007cea0, 0x2, 0x2})
            	/usr/local/go/src/reflect/value.go:339 +0xbf
            testing.(*F).Fuzz.func1.1(0x0?)
            	/usr/local/go/src/testing/fuzz.go:337 +0x231
            testing.tRunner(0xc000113860, 0xc00014c480)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*F).Fuzz.func1
            	/usr/local/go/src/testing/fuzz.go:324 +0x5b8
            
    
FAIL
exit status 1
FAIL	github.com/wmnsk/go-gtp/gtpv2/message	0.073s
```

**Comment by mogaika** [comment]
Oh, I also implemented very basic fuzz tests for ie parser and found a lot of similar bugs. Like 99% of them is not possible to catch with eye. Common ones:
```
if len(i.Payload) < 9 { // This should be <= instead
   return nil, io.ErrUnexpectedEOF
}
n = int(i.Payload[9])
```
```
if l < int(2+p.Length) { // This should be 2+int(p.Length), because p.Length is uint8 and after +2 it can overflow
    return io.ErrUnexpectedEOF
}
```
Branch of possible merge request https://github.com/mogaika/go-gtp/tree/fuzz
